- name: Test Ansible Playbooks
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Ansible playbook syntax
      #command: "ansible-playbook --syntax-check Setup_tasks/kafka-setup-exmpl_0.yml"
      ansible.builtin.command:
        argv:
        - ansible-playbook
        - --syntax-check
        - /home/ans/Downloads/Ansible_Wrk/Setup_tasks/kafka-setup-exmpl_0.yml
      register: syntax_check
      changed_when: false

    - name: Display Syntax Check Results
      ansible.builtin.debug:
        msg: "{{ syntax_check.stdout_lines }}"

    - name: Run playbook in check mode (dry run)
      command: ansible-playbook --check /home/ans/Downloads/Ansible_Wrk/Setup_tasks/kafka-setup-exmpl_0.yml
      register: dry_run
      changed_when: false

    - name: Display Dry Run Results
      ansible.builtin.debug:
        msg: "{{ dry_run.stdout_lines }}"
