---
    - name: Create directory
      file:
        path: /home/ans/mydata2
        state: directory

    - name: install apache2
      become: yes
      apt: name=apache2 update_cache=yes state=latest

#Start & enable a Service/server
    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes

# #check status of service and register output
#     - name: Get status of apache2
#       command: service apache2 status
#       register: apache_server_status
#       changed_when: false

#     - name: Display status
#       debug:
#         msg: "Status: {{ apache_server_status.stdout }}"

# #check status but using service module
#More Reliable: Works across different Linux distributions using their native service managers.
#Idempotent: Runs only if the service is not already in the desired state.
#Easier to Read & Maintain: More concise and readable than command: systemctl status apache2.
#No Need for changed_when: false: Unlike command, service properly detects changes.  

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Check Apache service status
      service:
        name: apache2
        state: started
      register: apache_status

    - name: Display status
      debug:
        msg: "Apache2 service is running"
        #var: apache_status.ActiveState
        #var: services_state