- name: Create directory
  file:
    path: /home/ans/mydata2
    state: directory

- name: install apache2
  become: yes
  apt: name=apache2 update_cache=yes state=latest

# #Start & enable a Service/server
# - name: Start and enable apache2
#   service:
#     name: apache2
#     state: started
#     enabled: yes

# #check status of service and register output
# - name: Get status of apache2
#   command: service apache2 status
#   register: apache_server_status

# - name: Display status
#   debug:
#     msg: "Status: {{ apache_server_status.stdout }}"