- name: Create directory
  file:
    path: /home/ans/mydata
    state: directory

- name: install apache2
  become: yes
  apt: name=apache2 update_cache=yes state=latest

#Start & enable a Service/server
- name: Start and enable nginx
  service:
    name: apache2
    state: started
    enabled: yes