- name: Monitor Disk Space
  hosts: all
  gather_facts: no
  tasks:
    - name: Get disk usage
      command: df -h /
      register: disk_usage

    - name: Show disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
    
    - name: Check CPU Load
      command: uptime
      register: cpu_load

    - name: Check Memory Usage
      command: free -m
      register: memory_usage

    - name: Display CPU Load
      debug:
        msg: "{{ cpu_load.stdout }}"

    - name: Display Memory Usage
      debug:
        msg: "{{ memory_usage.stdout_lines }}"
