- name: Manage hosts if behind a firewall
  hosts: all
  become: yes
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow Ansible SSH
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22

- name: Setup Admin Users
  hosts: all
  become: yes
  tasks:

    - name: Ensure 'adminuser' group exists
      ansible.builtin.group:
        name: adminuser
        state: present

    - name: Create admin users and add to 'adminuser' group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: adminuser
        append: yes
        state: present
      loop:
        - ans
        - ans2
        - ans3

    - name: Create home directories with a pause of 2 seconds
      ansible.builtin.file:
        path: "/home/{{ item }}"
        state: directory
        owner: "{{ item }}"
        group: adminuser
        mode: '0755'
      loop:
        - ans
        - ans2
        - ans3
      loop_control:
        pause: 2  # Adds a 2-second delay between each iteration

    - name: Grant sudo access to admin users
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/adminusers
        line: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        validate: 'visudo -cf %s'
      loop:
        - ans
        - ans2
        - ans3

    - name: Verify if users have sudo access
      command: sudo -l -U {{ item }}
      register: sudo_check_results
      ignore_errors: yes
      loop:
        - ans
        - ans2
        - ans3

    - name: Display sudo access check results
      ansible.builtin.debug:
        #msg: "{{ sudo_check_results.results}}"
        var: sudo_check_results
