- name: Manage hosts behind a firewall using accelerated mode
  hosts: all
  become: yes
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Enable UFW
      ufw:
        state: enabled

    #when and if using accelerated mode
    - name: Allow Ansible SSH and Accelerated Mode Port
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
      # - 5099
    
- name: Remove and Reinstall Apache on Web Servers
  hosts: webservers
  become: yes
  tasks:
    - name: Stop Apache service if running
      service:
        name: apache2
        state: stopped
      ignore_errors: yes  # Avoid failures if Apache is not installed

    - name: Remove Apache package
      apt:
        name: apache2
        state: absent
        purge: yes
    #   when: "'apache2' in ansible_facts.packages"
    #The commented-out line when: "'apache2' in ansible_facts.packages" is not needed 
    #because Ansible will gracefully handle package removal even if it's not installed.

    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    #when and if using accelerated mode
    # - name: Create a test file
    #   copy:
    #     content: "This is a test file for accelerated mode"
    #     dest: /tmp/testfile.txt
