- name: Install and start the service
  hosts: myhost
  become: yes
  vars:
    package_name:
      - docker.io
      - docker-compose
    service_name: docker  # Adjust if different

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes

    - name: Ensure the service is running
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
        enabled: yes  # Ensures service starts on boot
