- name: Test Ansible Playbooks
  hosts: all
  gather_facts: no
  tasks:

    - name: Check Ansible playbook syntax
      ansible.builtin.command: "ansible-playbook --syntax-check main.yml"
      register: syntax_check
      changed_when: false

    - name: Display Syntax Check Results
      ansible.builtin.debug:
        msg: "{{ syntax_check.stdout_lines }}"

    - name: Run playbook in check mode (dry run)
      ansible.builtin.command: "ansible-playbook --check main.yml"
      register: dry_run
      changed_when: false

    - name: Display Dry Run Results
      ansible.builtin.debug:
        msg: "{{ dry_run.stdout_lines }}"
